package page.child;

public final class Constants {
	 public static final String SELECTED_ENGLISH_LANGUAGE_FOR_MOBILE_DEVICE = "//span[text()='English']";
	 public static final String MOBILE_DEVICE_LANGUAGE_SELECTOR = "//div[@class='ru']";
     public static final String MOBILE_VERSION_BUTTON = "//a[@class='toMobile']";
     public static final String WEB_DRIVE_TYPE = "webdriver.chrome.driver";
     public static final String WEB_DRIVER_EXE_PATH = "C:\\Users\\USER\\Downloads\\chromedriver_win32\\Chromedriver.exe";
     public static final String URL = "http://totobet.am";
     public static final String CLICK_SPORT_BUTTON = "//a[@href='https://sport.totogaming.am/SportsBook/Home/index?l=en&d=d']";
     public static final String JS_LOGIC_FOR_PAGE_SCROLLING = "window.scrollBy(0,Math.max(document.documentElement.scrollHeight,document.body.scrollHeight,document.documentElement.clientHeight));";
     public static final String LOGIN_BUTTON = "//a[@class='btnLoginHeader secBtn transAll']";
     public static final String INPUT_LOGIN_FIELD = "//input[@id='login']";
     public static final String LOGIN = "totobasket";
     public static final String INPUT_PASSWORD_FIELD = "//input[@id='password']";
     public static final String PASSWORD = "toto1";
     public static final String CLICK_TO_LOGIN = "//*[@id='login_dialogue']/input";
     public static final String USERNAME = "//label[@class='value ']//div[contains(text(), 'totobasket')]";
     public static final String WEB_PAGE_LANGUAGE_SELECTOR = "//div[@class='sportHeaderLang secClr']//div[@class='lang ru']";
     public static final String SELECTED_ENGLISH_LANGUAGE_FOR_WEB_PAGE = "//div[@class='dropdown-content']//div[@class='lang en']";
     public static final String IMAGE_OF_GREAT_BRITAIN_FLAG = "//a[@class='flex dropdown-menu']//img[@src='/img/flags/en.png']";
     public static final String CHOOSE_FOOTBALL_ON_LEFT_MENU = "//span[@class='leftMenutxt txtColorPrm oe' and text()='Football']";
     public static final String CHOOSE_EUROPE_FROM_FOOTBALL = "//span[@class='leftMenutxt txtColorSec oe' and contains(text(), 'Europe')]";
     public static final String CHOOSE_UEFA_CHAMPIONS_LEGUE_FROM_EUROPE = "//span[@class='leftMenutxt txtColorSec oe' and contains(text(), 'UEFA Champions League (')]";
     public static final String PRESS_ON_FIRST_ODD_ON_FIRST_GAME = "(//div[@class='prematch_stake_odd_factor l_od Decimal'])[1]";
     public static final String INPUT_FIELD_FOR_BETTING = "//div[@class='betAmountRow displayFlex']//input[@id='betAmountInput']";
     public static final String INPUT_MONEY = "10";
     public static final String PRESS_PLACE_BET_BUTTON = "//input[@class='btn_bet ternBtn ns transAll']";
     public static final String ERROR_MESSAGE_ABOUT_MIN_BET = "//div[text()='Min. bet amount is 50, max. 500000']" ;//div[@class='err']";
     public static final String RESULTS_BUTTON = "(//a[@href='/SportsBook/Results'])[1]";
     public static final String CLICK_ALL_FROM_RESULTS = "//div[@id='res_cmb_ev']";
     public static final String CHOOSE_ENGLAND_FROM_ALL_MENU = "//div[@class='valueList ']//div[@title='England']";
     public static final String PRESS_SHOW_BUTTON_IN_RESLUTS = "//input[@id='res_btn_show']";
     public static final String PRESS_STATISTICS = "//a[@class='sm ic' and @href='javascript:OpenStatPage()']";
     public static final String PRESS_HANDBALL_FROM_STATISTICS = "//div[@style='border-bottom:solid 1px #333;']//a[@id='button_sp_10']";
     public static final String PRESS_EUROPE_FROM_HANDBALL_STATISTICS = "//a[@id='button_cont_10_1']";
     public static final String CHOOSE_SPAIN_FROM_EUROPE = "//a[@id='button_cnt_10_169']";
     public static final String CHOOSE_NATIONAL_CUP_FROM_SPAIN = "//a[@class='menuCompName menuCompName_1254']";
     public static final String PRESS_REGULATIONS = "//a[@class='sm ic'and @href='https://rules.totogaming.am/?l=en&m=4&s=4']";
     public static final String PRESS_LOGOUT = "(//div[@class='item '])[7]";
     public static final String CUT_LIVETV_FROM_SITE = "//div[@class='selectorWrapper displayFlex']//div[@class='chb_control']";
     public static final String LIVE_TV_WINDOW = "//div[@class='infoPanelDragger']";
     public static final String PLACE_TO_DRAG_LIVETV = "//div[@id='sportHeaderPanewatch']";
     public static final String TV_ICON = "//div[@class='ro_item ro_item3 transition200ms mn_border sportIcon header_reposition_icon']";
     public static final String MENU_ICON = "//div[@class='ro_item ro_item1 transition200ms mn_border sportIcon header_reposition_icon']";
     public static final String CLICK_TO_LIVETV = "//div[@class='tab_selector']//span[text()='Live TV']";
     public static final String OPEN_LIVETV_LIST = "(//div[@class='dropDownControl '])[3]";
     public static final String CHOOSE_SECOND_LIVE_MATCH = "((//div[@class='valueList '])[3]//i[@class='sportIcon'])[2]";
     public static final String CLICK_CALCULATOR = "//a[@href='javascript:BetCalculator.show();']";
     public static final String CHANGE_CALCULATOR_SYSTEM_STANDART = "//div[@id='calcSwitch']//label[@class='onOffSwitchLabel']";
     public static final String CLICK_SYSTEM_OPTION = "//div[@id='calc_new_systemType']";
     public static final String CHOOSE_FROM_OPTIONS_2_4 = "(//div[@class='valueList ' and @style='display: block;']//div[@class='item '])[1]";
     public static final String FIRST_INPUT_FIELD_FOR_ODD = "(//input[@class='coeff textbox'])[1]";
     public static final String SECOND_INPUT_FIELD_FOR_ODD = "(//input[@class='coeff textbox'])[2]";
     public static final String THIRD_INPUT_FIELD_FOR_ODD = "(//input[@class='coeff textbox'])[3]";
     public static final String FOURTH_INPUT_FIELD_FOR_ODD = "(//input[@class='coeff textbox'])[4]";
     public static final String UNCHECK_THIRD_FIELD = "//label[@for='ch3']";
     public static final String CALCULATE_BUTTON = "//input[@class='btn primBtn transAll oe']";
     public static final String CHECK_NUMBER_OF_OPTIONS = "//div[@class='numbOfV']//span[text()='6']";
     public static final String LOGO = "//div[@class='tl_logo']";
     public static final String CLICK_ON_LIVE = "//a[@id = 'mainLiveBtn']";
 	 public static final String HOME_PAGE = "//a[@href='/SportsBook/Home']";
	 public static final String LANGUAGE_SELECTOR = "//a[@class='flex dropdown-menu']";
	 public static final String CHOOSE_ENGLISH = "//span[@class='noshr lang en']";
	 public static final String REGISTER_BUTTON = "//a[@class='btnRegisterHeader primBtn transAll oe']";
   	 public static final String REGISTER_USER_NAME = "//input[@id='UserName']";
	 public static final String REGISTER_FIRST_NAME = "//input[@id='FirstName']";
	 public static final String SELECT_COUNTRY = "(//div[@class='tl_sel_custom_popup_reg_selected'])[5]";
	 public static final String ENTER_EMAIL = "//input[@id='Email']";
	 public static final String REGISTER_LAST_NAME = "//input[@id='LastName']";
	 public static final String SELECT_CITY = "(//div[@class='tl_sel_custom_popup_reg_selected'])[6]";
	 public static final String CHOOSE_DATE = "(//div[@class='tl_sel_custom_popup_reg_selected'])[1]";
	 public static final String CHOOSE_MONTH = "(//div[@class='tl_sel_custom_popup_reg_selected'])[2]";
	 public static final String CHOOSE_YEAR = "(//div[@class='tl_sel_custom_popup_reg_selected'])[3]";
	 public static final String ENTER_PASSWORD = "//input[@id='Password']";
	 public static final String CONFIRM_PASSWORD = "//input[@id='PasswordValidation']";
	 public static final String ENTER_ADRESS = "//input[@id='Address']";
	 public static final String MOBILE_NUMBER = "//input[@id='Mobile']";
	 public static final String ENTER_PASPORT = "//input[@id='PassportNumber']";
	 public static final String CAPTCHA = "//input[@id='Captcha']";
	 public static final String AGREE_CHECK = "(//span[@class='flex'])[3]";
	 public static final String REGISTER = "//button[@class='reg_btn btnSec transBg register_btn']";
}
